/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Transaksi;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DeleteTreatment extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteTreatment.class.getName());
// 1. TAMBAHKAN FIELD UNTUK MENYIMPAN ID TREATMENT
    private String idTreatmentToDelete; 
    private DataKlinikKecantikan parentFrame;
    /**
     * Konstruktor default (tetap pertahankan)
     */
    public DeleteTreatment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    // 2. TAMBAHKAN KONSTRUKTOR YANG MENERIMA ID TREATMENT
    public DeleteTreatment(java.awt.Frame parent, boolean modal, String idTreatment) {
        super(parent, modal);
        initComponents();
        
        // Simpan ID yang dikirimkan
        this.idTreatmentToDelete = idTreatment; 
        
        // Tampilkan ID di label agar pengguna yakin data mana yang dihapus
        jlabelDelete.setText(idTreatment); 
        this.setLocationRelativeTo(parent); // Posisikan dialog di tengah parent
    }
    
        public void setParentFrame(DataKlinikKecantikan parent) {
        this.parentFrame = parent;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabelDelete = new javax.swing.JLabel();
        jYa = new javax.swing.JButton();
        jTidak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(181, 111, 122));
        jPanel1.setForeground(new java.awt.Color(181, 111, 122));

        jlabelDelete.setBackground(new java.awt.Color(255, 255, 255));
        jlabelDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabelDelete.setForeground(new java.awt.Color(255, 255, 255));
        jlabelDelete.setText("> ");

        jYa.setBackground(new java.awt.Color(206, 150, 147));
        jYa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jYa.setForeground(new java.awt.Color(255, 255, 255));
        jYa.setText("Ya");
        jYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYaActionPerformed(evt);
            }
        });

        jTidak.setBackground(new java.awt.Color(206, 150, 147));
        jTidak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTidak.setForeground(new java.awt.Color(255, 255, 255));
        jTidak.setText("Tidak");
        jTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidakActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APAKAH ANDA YAKIN INGIN MENGHAPUS DATA ?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jYa)
                        .addGap(45, 45, 45)
                        .addComponent(jTidak)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jYa)
                    .addComponent(jTidak))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYaActionPerformed
        if (jlabelDelete.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else {
            String idTreatment = jlabelDelete.getText().trim();

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_P12PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            try {
                // cari pasien berdasarkan kolom id_pasien
                TypedQuery<DataTreatmentEntity> query = em.createQuery(
                    "SELECT p FROM DataTreatmentEntity p WHERE p.idTreatment = :id_treatment",
                    DataTreatmentEntity.class
                );
                query.setParameter("id_treatment", idTreatment);
                DataTreatmentEntity pasien = null;

                try {
                    pasien = query.getSingleResult();
                } catch (Exception e) {
                    pasien = null;
                }

                if (pasien == null) {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                    em.getTransaction().rollback();
                } else {
                    em.remove(em.contains(pasien) ? pasien : em.merge(pasien));
                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    dispose();
                    
                    if (parentFrame != null) {
                        parentFrame.showTableTreatment(); // refresh tabel pasien// opsional: refresh tabel treatment juga jika perlu
                    }// tutup dialog setelah hapus
                }
                

            } catch (Exception e) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
                e.printStackTrace();
            } finally {
                em.close();
                emf.close();
            }
        }
    }//GEN-LAST:event_jYaActionPerformed

    private void jTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidakActionPerformed
        dispose();
    }//GEN-LAST:event_jTidakActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jTidak;
    private javax.swing.JButton jYa;
    private javax.swing.JLabel jlabelDelete;
    // End of variables declaration//GEN-END:variables
}
