/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Transaksi;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class InsertTreatment extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(InsertTreatment.class.getName());
    private EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_P12PU");
    private DataKlinikKecantikan parentFrame;

    public InsertTreatment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        tfNamaTreatment.setEditable(false);
        tfHarga.setEditable(false);
        loadPasien();

    }

    public void setParentFrame(DataKlinikKecantikan parentFrame) {
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfIdTreatment = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        tfTanggal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNamaTreatment = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbDokter = new javax.swing.JComboBox<>();
        cbId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(181, 111, 122));

        jLabel1.setBackground(new java.awt.Color(181, 111, 122));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSERT DATA TREATMENT");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Treatment");

        jLabel4.setBackground(new java.awt.Color(181, 111, 122));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dokter");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");

        jLabel6.setBackground(new java.awt.Color(181, 111, 122));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal");

        tfIdTreatment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tfHarga.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tfTanggal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(206, 150, 147));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Pasien");

        tfNamaTreatment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Treatment");

        cbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Anisa", "Dr. Ben", "Dr. Isabella", "Dr. Anna" }));
        cbDokter.setToolTipText("");
        cbDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDokterActionPerformed(evt);
            }
        });

        cbId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfIdTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(cbId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(cbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfNamaTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                                .addComponent(tfHarga)
                                                .addComponent(tfTanggal))
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cbId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tfIdTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(tfNamaTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfIdTreatment.getText().isEmpty()
                || tfHarga.getText().isEmpty()
                || tfTanggal.getText().isEmpty()
                || cbId.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Semua data harus diisi dan pasien harus dipilih!");
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_P12PU");
        EntityManager em = emf.createEntityManager();

        String idTreatment = tfIdTreatment.getText().trim();
        String selectedPasienId = (String) cbId.getSelectedItem();
        if (selectedPasienId == null) {
            JOptionPane.showMessageDialog(this, "Pilih pasien terlebih dahulu!");
            return;
        }

        //Cek ID Treatment spy nggk sama dengan ID Pasien
        if (idTreatment.equals(selectedPasienId)) {
            JOptionPane.showMessageDialog(this,
                    "ID Treatment dan ID Pasien tidak boleh sama!",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);

            return;
        }

        String tanggalString = tfTanggal.getText().trim();

        // 1. Validasi Format Tanggal (String/VARCHAR)
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false); // Memaksa format ketat

        try {
            // Lakukan parsing HANYA untuk validasi. Jika gagal, akan melempar ParseException.
            sdf.parse(tanggalString);

        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this,
                    "Format tanggal salah! Gunakan yyyy-MM-dd (Contoh: 2023-12-31)",
                    "Kesalahan Input Tanggal",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada input tanggal: " + e.getMessage());
            return;
        }

        try {
            em.getTransaction().begin();

            // 2. Cek apakah ID Treatment sudah digunakan (Pengecekan di Level Aplikasi)
            DataTreatmentEntity existingTreatment = em.find(DataTreatmentEntity.class, idTreatment);

            if (existingTreatment != null) {
                JOptionPane.showMessageDialog(this,
                        "ID Treatment " + idTreatment + " sudah digunakan. Mohon gunakan ID lain.",
                        "Duplikasi ID",
                        JOptionPane.WARNING_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            // 3. Ambil Pasien
            PasienKecantikanEntity pasien = em.find(PasienKecantikanEntity.class, selectedPasienId);
            if (pasien == null) {
                JOptionPane.showMessageDialog(this, "Pasien dengan ID " + selectedPasienId + " tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }

            // 4. Buat dan isi objek DataTreatmentEntity
            DataTreatmentEntity treatment = new DataTreatmentEntity();
            treatment.setIdTreatment(idTreatment);
            treatment.setPasien(pasien); // Set relasi Pasien
            treatment.setDokter(cbDokter.getSelectedItem().toString());
            treatment.setNamaTreatment(tfNamaTreatment.getText().trim());

            // Konversi harga ke BigDecimal
            BigDecimal harga;
            try {
                harga = new BigDecimal(tfHarga.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Harga harus berupa angka yang valid.");
                em.getTransaction().rollback();
                return;
            }
            treatment.setHarga(harga);

            //  Set tanggal SEBAGAI STRING yang sudah divalidasi formatnya
            treatment.setTanggal(tanggalString);

            // 5. Simpan ke database
            em.persist(treatment);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data treatment berhasil disimpan!");

            if (parentFrame != null) {
                parentFrame.showTableTreatment();
            }
            dispose();

        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }

            // Error Umum Lainnya
            JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan data: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            logger.severe("Error: " + e.getMessage());
        } finally {
            em.close();
            // emf.close() dihindari di sini
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDokterActionPerformed
        String selectedDoctor = (String) cbDokter.getSelectedItem();
        if (selectedDoctor == null) {
            return;
        }

        switch (selectedDoctor) {
            case "Dr. Anisa":
                tfNamaTreatment.setText("Facial Premium");
                tfHarga.setText("200000");
                break;
            case "Dr. Ben":
                tfNamaTreatment.setText("Laser Acne");
                tfHarga.setText("350000");
                break;
            case "Dr. Isabella":
                tfNamaTreatment.setText("Botox Treatment");
                tfHarga.setText("500000");
                break;
            case "Dr. Anna":
                tfNamaTreatment.setText("Peeling Glow");
                tfHarga.setText("250000");
                break;
            default:
                tfNamaTreatment.setText("");
                tfHarga.setText("");
                break;
        }

    }//GEN-LAST:event_cbDokterActionPerformed

    private void cbIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdActionPerformed
        String selectedId = (String) cbId.getSelectedItem();
        if (selectedId != null) {
            System.out.println("Pasien dipilih: " + selectedId);
            // Bisa set field lain terkait pasien di sini
        }

    }//GEN-LAST:event_cbIdActionPerformed

    private void loadPasien() {
        cbId.removeAllItems(); // Kosongkan dulu

        EntityManager em = emf.createEntityManager();
        try {
            List<PasienKecantikanEntity> pasienList = em.createQuery(
                    "SELECT p FROM PasienKecantikanEntity p", PasienKecantikanEntity.class
            ).getResultList();

            String lastAddedId = null; // simpan ID pasien terakhir
            for (PasienKecantikanEntity pasien : pasienList) {
                cbId.addItem(pasien.getId()); // Sesuaikan getter ID
                lastAddedId = pasien.getId(); // update setiap iterasi, ID terakhir akan dipakai
            }

            // Pilih pasien terakhir secara otomatis
            if (lastAddedId != null) {
                cbId.setSelectedItem(lastAddedId);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal memuat data pasien: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            em.close();
        }
    }

    private void refreshPasien() {
        cbId.removeAllItems();
        EntityManager em = emf.createEntityManager();
        try {
            List<PasienKecantikanEntity> pasienList = em.createQuery(
                    "SELECT p FROM PasienKecantikanEntity p", PasienKecantikanEntity.class
            ).getResultList();

            for (PasienKecantikanEntity pasien : pasienList) {
                cbId.addItem(pasien.getId());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Gagal memuat data pasien: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            em.close();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDokter;
    private javax.swing.JComboBox<String> cbId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfIdTreatment;
    private javax.swing.JTextField tfNamaTreatment;
    private javax.swing.JTextField tfTanggal;
    // End of variables declaration//GEN-END:variables
}
