/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Transaksi;

import java.math.BigDecimal;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UpdateTreatment extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateTreatment.class.getName());
    private EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_P12PU");

    private boolean isLoading = false;
    private String idTreatment;

    // ← deklarasi flag updated di sini
    private boolean updated = false;

    // getter agar JFrame utama bisa cek
    public boolean isUpdated() {
        return updated;
    }

    /**
     * Creates new form UpdateTreatment
     */
    public UpdateTreatment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tfIdTreatment.setEditable(false);
        tfHarga.setEditable(false);
        tfTreatment.setEditable(false);
        cbId.setEditable(false);
        cbId.setEnabled(false);

    }

    public void setDataTreatment(String idTreatment, String idPasien, String namaTreatment, String harga, String tanggal, String dokter) {
        isLoading = true;
        this.idTreatment = idTreatment; // simpan untuk referensi loadTreatment
        loadTreatment(idTreatment);
        tfIdTreatment.setText(idTreatment);
        cbId.setSelectedItem(idPasien);
        cbDokter.setSelectedItem(dokter); // listener tidak jalan karena isLoading = true
        tfTreatment.setText(namaTreatment);
        tfHarga.setText(harga);
        tfTanggal.setText(tanggal);
        isLoading = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfIdTreatment = new javax.swing.JTextField();
        tfTreatment = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        tfTanggal = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbId = new javax.swing.JComboBox<>();
        cbDokter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(181, 111, 122));

        jLabel1.setBackground(new java.awt.Color(181, 111, 122));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATE DATA TREATMENT");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Treatment");

        jLabel3.setBackground(new java.awt.Color(181, 111, 122));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Treatment");

        jLabel4.setBackground(new java.awt.Color(181, 111, 122));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dokter");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");

        jLabel6.setBackground(new java.awt.Color(181, 111, 122));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal");

        tfIdTreatment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tfTreatment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tfHarga.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tfTanggal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btSave.setBackground(new java.awt.Color(206, 150, 147));
        btSave.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btSave.setText("SAVE");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Pasien");

        cbId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdActionPerformed(evt);
            }
        });

        cbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Anisa", "Dr. Ben", "Dr. Isabella", "Dr. Anna" }));
        cbDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDokterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btSave)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)))
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(tfHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(tfIdTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(tfTreatment, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(cbId, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDokter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btSave)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed

        EntityManager em = emf.createEntityManager(); // gunakan emf yang sudah ada di kelas

        try {
            em.getTransaction().begin();

            String idTreatment = tfIdTreatment.getText().trim();
            DataTreatmentEntity treatment = em.find(DataTreatmentEntity.class, idTreatment);

            if (treatment != null) {
                // Ambil ID pasien dari combo box
                String idPasien = cbId.getSelectedItem().toString();

                // Ambil entitas pasien berdasarkan id_pasien
                PasienKecantikanEntity pasien = em.find(PasienKecantikanEntity.class, idPasien);
                if (pasien == null) {
                    JOptionPane.showMessageDialog(this, "Pasien dengan ID tersebut tidak ditemukan!");
                    em.getTransaction().rollback();
                    return;
                }

                // Set hubungan parent (FK)
                treatment.setPasien(pasien);

                // Set data lain
                treatment.setNamaTreatment(tfTreatment.getText().trim());

                BigDecimal harga;
                try {
                    harga = new BigDecimal(tfHarga.getText().trim());
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Harga harus berupa angka yang valid.");
                    em.getTransaction().rollback();
                    return;
                }
                treatment.setHarga(harga);

                String selectedIdPasien = cbId.getSelectedItem().toString();
                String selectedDokter = cbDokter.getSelectedItem().toString();
                String selectedTanggal = tfTanggal.getText().trim();

                List<DataTreatmentEntity> checkDuplicate = em.createQuery(
                        "SELECT d FROM DataTreatmentEntity d WHERE d.pasien.id = :id AND d.dokter = :dokter AND d.tanggal = :tanggal AND d.idTreatment <> :idTreatment",
                        DataTreatmentEntity.class
                )
                        .setParameter("id", selectedIdPasien)
                        .setParameter("dokter", selectedDokter)
                        .setParameter("tanggal", selectedTanggal)
                        .setParameter("idTreatment", idTreatment)
                        .getResultList();

                if (!checkDuplicate.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Data treatment untuk pasien, dokter, dan tanggal ini sudah ada!");
                    em.getTransaction().rollback();
                    return;
                }

                treatment.setDokter(cbDokter.getSelectedItem().toString());
                em.merge(treatment);
                em.getTransaction().commit();

                // Set flag updated = true agar JFrame utama tahu data berubah
                updated = true;

                JOptionPane.showMessageDialog(this, "Data treatment berhasil diperbarui!");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Data treatment tidak ditemukan!");
            }

        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        } finally {
            em.close();
            // jangan close emf di sini
            // emf.close();
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void cbIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdActionPerformed
        String selectedId = (String) cbId.getSelectedItem();
        if (selectedId != null) {
            System.out.println("Pasien dipilih: " + selectedId);
            // Bisa set field lain terkait pasien di sini
        }
    }//GEN-LAST:event_cbIdActionPerformed

    private void cbDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDokterActionPerformed
    if (isLoading) return; // ⛔ pastikan gak dijalankan saat load data

    String selectedDokter = (String) cbDokter.getSelectedItem();
    if (selectedDokter != null) {
        updateTreatmentFromDoctor(selectedDokter); // ✅ ini hanya jalan kalau user ubah dokter
    }
    }//GEN-LAST:event_cbDokterActionPerformed

    private void updateTreatmentFromDoctor(String dokter) {
        switch (dokter) {
            case "Dr. Anisa":
                tfTreatment.setText("Facial Premium");
                tfHarga.setText("200000");
                break;
            case "Dr. Ben":
                tfTreatment.setText("Laser Acne");
                tfHarga.setText("350000");
                break;
            case "Dr. Isabella":
                tfTreatment.setText("Botox Treatment");
                tfHarga.setText("500000");
                break;
            case "Dr. Anna":
                tfTreatment.setText("Peeling Glow");
                tfHarga.setText("250000");
                break;
            default:
                tfTreatment.setText("");
                tfHarga.setText("");
                break;
        }
    }

    private void loadTreatment(String idTreatment) {
        EntityManager em = emf.createEntityManager();

        try {
            if (idTreatment != null && !idTreatment.isEmpty()) {
                DataTreatmentEntity tr = em.find(DataTreatmentEntity.class, idTreatment);
                if (tr != null) {
                    isLoading = true;

                    // isi combo box pasien
                    cbId.removeAllItems();
                    List<PasienKecantikanEntity> pasienList = em.createQuery("SELECT p FROM PasienKecantikanEntity p", PasienKecantikanEntity.class).getResultList();
                    for (PasienKecantikanEntity p : pasienList) {
                        cbId.addItem(p.getId());
                    }

                    // isi field dari database
                    tfIdTreatment.setText(tr.getIdTreatment());
                    cbId.setSelectedItem(tr.getPasien().getId());
                    cbDokter.setSelectedItem(tr.getDokter());
                    tfTreatment.setText(tr.getNamaTreatment());
                    tfHarga.setText(tr.getHarga().toString());
                    tfTanggal.setText(tr.getTanggal().toString());

                    // form selesai load
                    isLoading = false;
                } else {
                    JOptionPane.showMessageDialog(this, "Data treatment tidak ditemukan!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data treatment: " + e.getMessage());
        } finally {
            em.close();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox<String> cbDokter;
    private javax.swing.JComboBox<String> cbId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfIdTreatment;
    private javax.swing.JTextField tfTanggal;
    private javax.swing.JTextField tfTreatment;
    // End of variables declaration//GEN-END:variables
}
