/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Transaksi;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UpdatePasien extends javax.swing.JDialog {
    // Perubahan: Menggunakan DataKlinikKecantikan sebagai referensi ke form utama
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdatePasien.class.getName());

    private DataKlinikKecantikan dataKlinikKecantikan;
    private boolean updated = false;

    // Perubahan: Menghapus tanggalLahir dan diagnosa, menyesuaikan tipe data noHp menjadi String
    public UpdatePasien(java.awt.Frame parent, boolean modal, DataKlinikKecantikan dataKlinikKecantikan,
            String id, String nama, String alamat, String noHp) {
        super(parent, modal);
        initComponents();
        this.dataKlinikKecantikan = dataKlinikKecantikan;

        tfId.setText(id);
        tfNama.setText(nama);
        tfAlamat.setText(alamat);
        tfNoHp.setText(noHp);
        tfId.setEditable(false);
    }

    public boolean isUpdated() {
        return updated;
    }

    // Konstruktor default untuk kompatibilitas NetBeans
    public UpdatePasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tfId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        tfNoHp = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 240, 230));

        jLabel1.setBackground(new java.awt.Color(181, 111, 122));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 111, 122));
        jLabel1.setText("UPDATE DATA PASIEN");

        jLabel2.setBackground(new java.awt.Color(181, 111, 122));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(181, 111, 122));
        jLabel2.setText("ID Pasien");

        jLabel3.setBackground(new java.awt.Color(181, 111, 122));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(181, 111, 122));
        jLabel3.setText("Nama");

        jLabel4.setBackground(new java.awt.Color(181, 111, 122));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(181, 111, 122));
        jLabel4.setText("Alamat");

        jLabel5.setBackground(new java.awt.Color(181, 111, 122));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(181, 111, 122));
        jLabel5.setText("No. HP");

        tfId.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tfAlamat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });

        tfNama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tfNoHp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        btSave.setBackground(new java.awt.Color(181, 111, 122));
        btSave.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btSave.setText("SAVE");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSave)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btSave)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
// Perubahan: Menyesuaikan validasi input dengan field yang ada
        if (tfId.getText().isEmpty() || tfNama.getText().isEmpty() || tfAlamat.getText().isEmpty()
                || tfNoHp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua data harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String id = tfId.getText().trim();
        String nama = tfNama.getText().trim();
        String alamat = tfAlamat.getText().trim();
        String noHp = tfNoHp.getText().trim(); // Perubahan: noHp menjadi String

        // Perubahan: Mengganti nama Persistence Unit
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBO_P12PU");
        EntityManager em = emf.createEntityManager();

        try {
            em.getTransaction().begin();

            // Perubahan: Menggunakan PasienKecantikanEntity
            PasienKecantikanEntity p = em.find(PasienKecantikanEntity.class, id);

            if (p == null) {
                JOptionPane.showMessageDialog(this, "Data pasien tidak ditemukan!");
            } else {
                // p.setId(id); // ID tidak perlu di-set ulang karena sudah primary key dan tidak diedit
                p.setNama(nama);
                p.setAlamat(alamat);
                p.setNoHp(noHp); // Perubahan: noHp di-set sebagai String

                // em.merge(p); // Menggunakan merge atau biarkan commit yang melakukan update
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
                updated = true;

                // Perubahan: Memanggil showTable() dari DataKlinikKecantikan
                if (dataKlinikKecantikan != null) {
                    dataKlinikKecantikan.showTable(); // refresh tabel
                }
                dispose();
            }

        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat update data: " + e.getMessage(), "Kesalahan Database", JOptionPane.ERROR_MESSAGE);

            // Hapus baris Logger yang bermasalah, pertahankan printStackTrace:
            e.printStackTrace();

            // Atau, jika ingin menambahkan pesan ke konsol secara manual:
            System.err.println("Error saat update data Pasien: " + e.getMessage());
            // e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_btSaveActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoHp;
    // End of variables declaration//GEN-END:variables
}
